In [1]:
import numpy as np

### Creating Array, Array Shape, Array Size & Array Datatypes

In [16]:
# 1-d array
a = np.array([1,2,3],dtype='int8')
print(a)

[1 2 3]


In [3]:
a

array([1, 2, 3])

In [18]:
# 2-d array
b = np.array([[1,2,3],[4.0,5.0,6.0]],dtype='int16')
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
# Get dimension
a.ndim

1

In [8]:
b.ndim

2

In [9]:
# Get Shape
a.shape

(3,)

In [10]:
b.shape

(2, 3)

In [11]:
# Get type
type(a)

numpy.ndarray

In [12]:
type(b)

numpy.ndarray

In [17]:
# Get datatype
a.dtype

dtype('int8')

In [19]:
b.dtype

dtype('int16')

In [20]:
# Get size

a.itemsize

1

In [21]:
b.itemsize

2

### Accessing/Changing specific elements,rows & columns

In [35]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [23]:
# get a specific element [row,col]

a[1,5]

13

In [24]:
# get a specific row

a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [25]:
#get a specific column

a[:,0]

array([1, 8])

In [29]:
# get elements using stepsize

a[0,::2]

array([1, 3, 5, 7])

In [31]:
# Changing an element
a[1,5] = 20

In [32]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [36]:
# changing all column elements
a[:,2] = 5
print(a)

a[:,2] = [21,22]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 13 14]]
[[ 1  2 21  4  5  6  7]
 [ 8  9 22 11 12 13 14]]


#### 3 Dimensional array

In [38]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [54]:
# get a specific element

b[0,1,1]

9

In [46]:
#replace
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [55]:
b[:,1,:] = [[10,11],[20,21]]

In [56]:
b

array([[[ 1,  2],
        [10, 11]],

       [[ 5,  6],
        [20, 21]]])

In [60]:
b[0,1,1]

11

In [61]:
b[1,0,0]

5

### Initializing different types of arrays

In [62]:
# all zero matrix
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [71]:
b = np.ones((2,3,4),dtype='int32')

In [72]:
b

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [73]:
b.itemsize

4

In [76]:
# any other number matrix

np.full((3,2,2),5,dtype='float32')

array([[[5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.]],

       [[5., 5.],
        [5., 5.]]], dtype=float32)

In [77]:
# Random decimal number
np.random.rand(3,2,2)

array([[[0.79690494, 0.68410865],
        [0.86695158, 0.58147427]],

       [[0.73855841, 0.41081275],
        [0.07255937, 0.53483054]],

       [[0.75120946, 0.07268916],
        [0.56616012, 0.30883853]]])

In [80]:
# random number

np.random.randint(10,size=(3,2,2))

array([[[8, 8],
        [4, 5]],

       [[6, 5],
        [1, 5]],

       [[6, 2],
        [9, 1]]])

In [83]:
np.random.randint(-5,10,size=(3,3,3)) # -5 is the lowest limit & 10 is the upper limit

array([[[-1, -4, -3],
        [ 9,  8, -2],
        [ 0,  0, -1]],

       [[ 3,  2,  5],
        [ 1,  5,  9],
        [ 1,  1,  6]],

       [[-3,  7,  8],
        [-3,  2,  1],
        [-4,  8, -3]]])

In [84]:
# indentity matrix

np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [86]:
# repeat array

ar = np.array([[1,2,3]])
r = np.repeat(ar,3,axis=0)
r


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [87]:
s = np.repeat(ar,4,axis=1)
s

array([[1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3]])

In [101]:
o = np.ones((5,5),dtype='int32')
print(o)
o[1:4,1:4] = [0]
print(o)
o[2,2] = 9
print(o)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


### Be careful when copying array!

In [102]:
a = np.array([1,2,3])
b=a
b[0] = -1
print(b)
print(a)

[-1  2  3]
[-1  2  3]


In [103]:
a = np.array([1,2,3])
b = a.copy()
b[0] = -1
print(b)
print(a)

[-1  2  3]
[1 2 3]


### Basic Mathematics

In [104]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [105]:
a - 2

array([-1,  0,  1,  2])

In [106]:
a+4

array([5, 6, 7, 8])

In [107]:
a*3

array([ 3,  6,  9, 12])

In [108]:
a/3

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [109]:
b = np.array([1,2,1,2])
a+b

array([2, 4, 4, 6])

In [110]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [111]:
a**5

array([   1,   32,  243, 1024], dtype=int32)

In [112]:
a**0.5

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [113]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [114]:
a*b

array([1, 4, 3, 8])

Linear Algebra

In [117]:
a = np.ones((3,3),dtype='int32')
print(a)

b = np.full((3,3),5)
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [118]:
np.matmul(a,b)

array([[15, 15, 15],
       [15, 15, 15],
       [15, 15, 15]])

In [120]:
c = np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [122]:
s = np.array([[1,2,3],[4,5,6]])
s

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
np.min(s)

1

In [124]:
np.max(s)

6

In [129]:
np.sum(s,axis=1)

array([ 6, 15])

In [128]:
np.sum(s,axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [132]:
# reshaping matrices
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape(8,1)
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [135]:
# vertical stack vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [136]:
# horizontal stack vectors
h1 = ([1,2,3,4])
h2 = ([5,6,7,8])

np.hstack([h1,h2])

array([1, 2, 3, 4, 5, 6, 7, 8])

### Load data using numpy

 It is possible to load data using numpy.

In [142]:
filedata = np.genfromtxt(r'C:\Users\lenovo\Desktop\data.txt', delimiter=',')
filedata

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [143]:
filedata.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]])

### Boolean Masking and Advanced Indexing

In [144]:
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [145]:
filedata[filedata>50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [146]:
# index with a list in numpy

a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])